### ISSUE TITLE
Удалить пустые эндпоинты

### ISSUE THREAD

**Issue by dsim01** [Krok-Todo-App/Todo-Back-End#3]
- [ ] api/Tasks - DELETE
- [ ] api​/Tasks​/test - GET

**Comment by EdvardPotapenko** [comment]
Профсоюз сказал что мы будем жаловаться на такие issue

**Comment by dsim01** [comment]
Простите я eblonk
![image](https://user-images.githubusercontent.com/23611265/115140277-39522280-a03f-11eb-836e-7520e4e483d4.png)

**Comment by Eminzzz** [comment]
![image](https://user-images.githubusercontent.com/23611265/115129626-4f84c200-9ff0-11eb-9078-5e112c852244.png)
